enableScripts: false
nmHoistingLimits: workspaces
nodeLinker: node-modules

npmPreapprovedPackages:
  - "dsh-codex-connect@0.1.0-alpha.4.20"

packageExtensions:
  "app-builder-lib@26.15.7":
    peerDependenciesMeta:
      electron-builder-squirrel-windows:
        optional: true

supportedArchitectures:
  os:
    - current
  cpu:
    - current
    - arm64
