enableScripts: false
nmHoistingLimits: workspaces
nodeLinker: node-modules

packageExtensions:
  "app-builder-lib@26.15.7":
    peerDependenciesMeta:
      electron-builder-squirrel-windows:
        optional: true

supportedArchitectures:
  os:
    - current
  cpu:
    - current
    - arm64
