import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

const source = await readFile(new URL('../src/client/components.tsx', import.meta.url), 'utf8')
const previewSource = await readFile(new URL('../src/client/file-drag-preview.ts', import.meta.url), 'utf8')
const hoverSource = await readFile(new URL('../src/client/file-hover-preview.tsx', import.meta.url), 'utf8')
const css = await readFile(new URL('../src/client/styles.css', import.meta.url), 'utf8')

describe('Project file tree presentation', () => {
  it('uses BEUI tree primitives while preserving project-specific behavior', () => {
    expect(source).toMatch(/import \{[^}]*FileTree[^}]*FileTreeFile[^}]*FileTreeFolder[^}]*\} from '@convax\/beui'/su)
    expect(source).toContain('<FileTreeFolder key={entry.path} value={entry.path} name={entry.name}>')
    expect(source).toContain('label={<ProjectFileName name={entry.name} />}')
    expect(source).toContain('previewUrl={previewSnapshot.thumbnails[entry.path]}')
    expect(source).not.toContain('<FileTreeFolder key={entry.path} value={entry.path} name={entry.name} icon=')
    expect(source).toContain("disabled={entry.kind === 'symlink'}")
    expect(source).toContain('expandedIds={snapshot.expanded}')
    expect(source).toContain('onExpandedChange={changeExpanded}')
    expect(source).toContain('runtime.toggleDirectory(path)')
    expect(source).toContain("draggable={entry.kind === 'file'}")
    expect(source).toContain('event.dataTransfer.setData(PROJECT_FILE_DRAG_MIME')
    expect(source).toContain('onPointerEnter={event => { previewHandlers.open(entry, event.currentTarget, false) }}')
    expect(source).toContain('onPointerLeave={() => { previewHandlers.close(entry) }}')
    expect(source).toContain('preview.setDragImage(event.dataTransfer, entry)')
    expect(source).toContain('encodeProjectFileDragPayload({')
    expect(source).toContain('workspaceId,')
    expect(source).toContain('path: entry.path,')
    expect(source).not.toContain('name: entry.name')
  })

  it('uses bounded content previews without widening the drag payload', () => {
    expect(previewSource).toContain('scope.previewFile(entry.path, controller.signal)')
    expect(previewSource).toContain('imageThumbnailUrl(content)')
    expect(previewSource).toContain('videoPosterUrl(content.mediaUrl, controller.signal)')
    expect(previewSource).toContain('scope.releasePreview(videoPreviewId)')
    expect(previewSource).toContain('URL.revokeObjectURL(')
    expect(hoverSource).toContain('<video')
    expect(hoverSource).toContain('autoPlay={!reduceMotion}')
    expect(hoverSource).toContain('<pre className="cvxProjectFileHoverPreviewText">')
    expect(previewSource).toContain('THUMBNAIL_CACHE_CAP = 32')
    expect(previewSource).toContain('THUMBNAIL_CONCURRENCY = 2')
    expect(previewSource).toContain('dataTransfer.setDragImage(preview, DRAG_PREVIEW_HOTSPOT, DRAG_PREVIEW_HOTSPOT)')
    expect(previewSource).not.toMatch(/setData\([^)]*(?:name|mime|url|bytes)/u)
    expect(previewSource).not.toContain('file:')
    expect(css).toMatch(/\.cvxProjectFileNamePrefix\s*\{[^}]*text-overflow:\s*ellipsis/su)
    expect(css).toMatch(/\.cvxProjectFileNameSuffix\s*\{[^}]*flex:\s*0 0 auto/su)
    expect(css).toMatch(/\.cvxProjectFileThumbnail\s*\{[^}]*object-fit:\s*cover/su)
    expect(css).toMatch(/\.cvxProjectFileHoverPreview\s*\{[^}]*position:\s*fixed[^}]*pointer-events:\s*none/su)
    expect(css).toMatch(/\.cvxProjectFileHoverPreviewText\s*\{[^}]*white-space:\s*pre-wrap/su)
  })

  it('keeps section collapse and the nested canvases seat around the tree', () => {
    expect(source).toContain('<AnimatedSidebarMenuItem')
    expect(source).toContain('className="cvxProjectSectionItem"')
    expect(source).toContain('variant="section"')
    expect(source).not.toContain('icon={<FolderIcon open={filesExpanded} size={18} />}')
    expect(source).toContain('expanded={filesExpanded}')
    expect(source).toContain('<AnimatedSidebarSubmenu expanded={filesExpanded} className="cvxProjectFilesMotion">')
    expect(source).not.toContain('hidden={!filesExpanded}')
    expect(source).not.toContain('cvxProjectNavigatorScroll')
    expect(source).toContain("renderSlot('project.canvases', { project: runtime })")
  })

  it('uses the BEUI project picker instead of a native select', () => {
    expect(source).toMatch(/import \{[^}]*Select[^}]*\} from '@convax\/beui'/su)
    expect(source).toContain('<Select')
    expect(source).toContain('ariaLabel="Active project"')
    expect(source).toContain('onValueChange={(workspaceId) => { run(runtime.switchWorkspace(workspaceId)) }}')
    expect(source).not.toContain('<select')
    expect(source).not.toContain('<option')
  })

  it('leaves global BEUI CSS to the UI owner and uses Button on safe Project and Agent actions', () => {
    expect(source).toContain('return <style>{css}</style>')
    expect(source).not.toContain('BEUI_THEME_CSS')
    expect(source).not.toContain('BEUI_COMPONENT_CSS')
    expect(source).toMatch(/<Button[^>]+aria-label="Add project"[^>]*>/u)
    expect(source).toContain('aria-label="Expand projects"')
    expect(source).toContain('className="cvxProjectButton cvxProjectRailButton"')
    expect(source).toContain('aria-label="Collapse Agent panel"')
    expect(source).toMatch(/<Button\s+variant="secondary"\s+size="sm"\s+className="cvxProjectAgentAction"/u)
    expect(source.match(/<Button\b/gu)).toHaveLength(5)
  })
})
