export const CANVAS_ERROR_CODES = {
  INVALID_JSON_VALUE: 'INVALID_JSON_VALUE',
  INVALID_PROJECT: 'INVALID_PROJECT',
  INVALID_DOCUMENT: 'INVALID_DOCUMENT',
  INVALID_NODE: 'INVALID_NODE',
  INVALID_EDGE: 'INVALID_EDGE',
  UNSUPPORTED_SCHEMA_VERSION: 'UNSUPPORTED_SCHEMA_VERSION',
  INVALID_PROJECT_ID: 'INVALID_PROJECT_ID',
  INVALID_CANVAS_ID: 'INVALID_CANVAS_ID',
  INVALID_WORKSPACE_ID: 'INVALID_WORKSPACE_ID',
  INVALID_NODE_ID: 'INVALID_NODE_ID',
  INVALID_EDGE_ID: 'INVALID_EDGE_ID',
  NODE_TYPE_NOT_REGISTERED: 'NODE_TYPE_NOT_REGISTERED',
  EDGE_TYPE_NOT_REGISTERED: 'EDGE_TYPE_NOT_REGISTERED',
  REVISION_CONFLICT: 'REVISION_CONFLICT',
  PATCH_INVALID_OPERATION: 'PATCH_INVALID_OPERATION',
  PATCH_INVALID_POINTER: 'PATCH_INVALID_POINTER',
  PATCH_FORBIDDEN_PATH: 'PATCH_FORBIDDEN_PATH',
  PATCH_PATH_NOT_FOUND: 'PATCH_PATH_NOT_FOUND',
  PATCH_NODE_ALREADY_EXISTS: 'PATCH_NODE_ALREADY_EXISTS',
  PATCH_EDGE_ALREADY_EXISTS: 'PATCH_EDGE_ALREADY_EXISTS',
} as const

export type CanvasErrorCode = (typeof CANVAS_ERROR_CODES)[keyof typeof CANVAS_ERROR_CODES]

export class CanvasContractError extends Error {
  readonly code: CanvasErrorCode
  readonly operationIndex: number | undefined

  constructor(code: CanvasErrorCode, message: string, operationIndex?: number) {
    super(message)
    this.name = 'CanvasContractError'
    this.code = code
    this.operationIndex = operationIndex
  }
}
